import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { buildRegistryReleaseArtifacts, verifyRegistryReleaseArtifacts } from "../../src/registry/release.js";
import { startInternalRegistry, type InternalRegistryFixture } from "../support/internal-registry.js";

const temporaryDirectories: string[] = [];
const registries: InternalRegistryFixture[] = [];

afterEach(async () => {
  await Promise.all(registries.splice(0).map((registry) => registry.close()));
  await Promise.all(temporaryDirectories.splice(0).map((directory) => fs.rm(directory, { recursive: true, force: true })));
});

describe("registry release verification", () => {
  it("rebuilds exact release inputs and rejects stale lock or generated bytes", async () => {
    const fixture = await buildFixture();
    await buildRegistryReleaseArtifacts(fixture.options);
    const firstLock = await fs.readFile(fixture.options.lockPath);
    const firstSnapshot = await fs.readFile(path.join(fixture.options.generatedRoot, "snapshot.json"));
    await fs.rm(fixture.options.lockPath);
    await fs.rm(fixture.options.generatedRoot, { recursive: true });
    await buildRegistryReleaseArtifacts(fixture.options);
    expect(await fs.readFile(fixture.options.lockPath)).toEqual(firstLock);
    expect(await fs.readFile(path.join(fixture.options.generatedRoot, "snapshot.json"))).toEqual(firstSnapshot);
    await expect(verifyRegistryReleaseArtifacts(fixture.options)).resolves.toMatchObject({ files: [
      "contributions/firm/example/fixtures/policy.json",
      "contributions/firm/example/policy.json",
      "contributions/firm/example/web-doctor.json",
      "snapshot.json",
    ] });

    await fs.appendFile(fixture.options.lockPath, " ", "utf8");
    await expect(verifyRegistryReleaseArtifacts(fixture.options)).rejects.toThrow(/changed registry\/registry\.lock\.json/);
    await buildRegistryReleaseArtifacts(fixture.options);

    await fs.writeFile(path.join(fixture.options.generatedRoot, "unexpected.txt"), "dirty", "utf8");
    await expect(verifyRegistryReleaseArtifacts(fixture.options)).rejects.toThrow(/unexpected generated\/registry\/unexpected\.txt/);
  });
});

async function buildFixture() {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), "web-doctor-release-"));
  temporaryDirectories.push(directory);
  const manifest = {
    schema: "web-doctor.contribution",
    schemaVersion: 1,
    id: "firm/example",
    type: "policy",
    owner: "Fixture Team",
    compatibility: { webDoctor: ">=0.1.0" },
    portals: [],
    layers: ["firmwide"],
    documents: [{ kind: "policy", path: "policy.json" }],
    runtimeArtifacts: [],
    dependencies: [],
    fixtures: ["fixtures/policy.json"],
    provenance: { repository: "ssh://git.internal/firm/example.git", commit: "e".repeat(40) },
  };
  const registry = await startInternalRegistry([{
    name: "@firm/example",
    version: "1.0.0",
    commit: "e".repeat(40),
    files: {
      "web-doctor.json": JSON.stringify(manifest),
      "policy.json": JSON.stringify({
        schema: "web-doctor.policy-pack",
        schemaVersion: 2,
        id: "firm/example",
        version: "1.0.0",
        owner: "Fixture Team",
        layer: "firmwide",
        compatibility: { webDoctor: ">=0.1.0" },
        controls: [{
          id: "firm/example/control",
          title: "Example control",
          rationale: "Exercise deterministic release assembly.",
          strength: "required",
          applicability: {},
          evidence: [{ provider: "eslint", rule: "example/rule", kind: "static", required: true }],
          verification: [{ kind: "test", description: "Run the contribution fixture." }],
        }],
      }),
      "fixtures/policy.json": JSON.stringify({
        schema: "web-doctor.fixture",
        schemaVersion: 1,
        id: "policy/accept",
        contract: "policyPack",
        input: "policy.json",
        expected: "accept",
      }),
    },
  }]);
  registries.push(registry);
  const catalogPath = path.join(directory, "catalog.json");
  const ownershipPath = path.join(directory, "ownership.json");
  await fs.writeFile(catalogPath, JSON.stringify({
    schema: "web-doctor.catalog",
    schemaVersion: 1,
    portals: [],
    entries: [{
      id: "firm/example",
      type: "policy",
      owner: "fixture-team",
      source: registry.source("@firm/example", "1.0.0"),
      manifestPath: "web-doctor.json",
      portals: [],
      layers: ["firmwide"],
      compatibility: { webDoctor: ">=0.1.0" },
      lifecycle: "active",
      dependencies: [],
    }],
  }), "utf8");
  await fs.writeFile(ownershipPath, JSON.stringify({
    schema: "web-doctor.registry-ownership",
    schemaVersion: 1,
    platformReviewTeam: "@platform/web-doctor",
    owners: [{
      id: "fixture-team",
      name: "Fixture Team",
      codeownersTeam: "@fixture/team",
      namespaces: ["firm"],
      portals: [],
    }],
  }), "utf8");
  return {
    options: {
      catalogPath,
      ownershipPath,
      lockPath: path.join(directory, "registry.lock.json"),
      generatedRoot: path.join(directory, "generated", "registry"),
      resolver: { registry: registry.registry, cache: registry.cache, allowInsecureRegistry: true },
      webDoctorVersion: "0.1.0",
      webDoctorCommit: "c".repeat(40),
      catalogCommit: "d".repeat(40),
    },
  };
}