import fs from "node:fs/promises";
import path from "node:path";

/**
 * Agent registration: an MCP server entry in each supported client's
 * project configuration, and a short generated instruction that sends
 * agents to the MCP server for project facts. The instruction is fixed text;
 * policy, guidance, and project facts stay behind the MCP server, so no
 * static file goes stale when a package release changes them. Install and
 * uninstall touch only Web Doctor's entry and marked block, and running
 * either twice changes nothing the second time.
 */

export const AGENT_CLIENTS = ["claude-code", "cursor", "vscode"] as const;
export type AgentClient = (typeof AGENT_CLIENTS)[number];

const SERVER_NAME = "web-doctor";
const BEGIN = "<!-- web-doctor:begin -->";
const END = "<!-- web-doctor:end -->";

interface ClientLayout {
  config: string;
  /** The JSON object that holds servers by name. */
  serversKey: "mcpServers" | "servers";
  instruction: string;
}

const LAYOUTS: Readonly<Record<AgentClient, ClientLayout>> = {
  "claude-code": { config: ".mcp.json", serversKey: "mcpServers", instruction: "CLAUDE.md" },
  cursor: { config: ".cursor/mcp.json", serversKey: "mcpServers", instruction: "AGENTS.md" },
  vscode: { config: ".vscode/mcp.json", serversKey: "servers", instruction: "AGENTS.md" },
};

/** The generated instruction. It names the tools and nothing about any policy. */
export const AGENT_INSTRUCTION = `${BEGIN}
## Web Doctor

The \`web-doctor\` MCP server answers questions about this application from current evidence. Ask it before assuming project facts, policy, or verification steps:

- \`project_overview\` and \`explain_symbol\` for architecture, components, and tests
- \`effective_guidance\` for the Controls and approved patterns that apply to a file
- \`run_diagnostics\` and \`explain_finding\` for findings and their obligations
- \`plan_upgrade\` and \`plan_verification\` for ordered changes and checks

Web Doctor never edits source. Its policy and guidance change with each package release, so do not copy them into this file.

This block is generated by \`web-doctor agent install\` and removed by \`web-doctor agent uninstall\`.
${END}
`;

export interface ServerLaunch {
  command: string;
  args: string[];
}

export interface RegistrationChange {
  client: AgentClient | null;
  file: string;
  action: "created" | "updated" | "unchanged" | "removed" | "absent";
}

export interface RegistrationOptions {
  /** Where client configuration lives, normally the repository root. */
  root: string;
  clients: readonly AgentClient[];
}

export async function installAgents(options: RegistrationOptions & { launch: ServerLaunch }): Promise<RegistrationChange[]> {
  const changes: RegistrationChange[] = [];
  for (const client of options.clients) {
    const layout = LAYOUTS[client];
    const entry = client === "vscode" ? { type: "stdio", command: options.launch.command, args: options.launch.args } : { command: options.launch.command, args: options.launch.args };
    changes.push({ client, file: layout.config, action: await editJson(path.join(options.root, layout.config), (config) => {
      const servers = isRecord(config[layout.serversKey]) ? { ...(config[layout.serversKey] as Record<string, unknown>) } : {};
      servers[SERVER_NAME] = entry;
      return { ...config, [layout.serversKey]: servers };
    }) });
  }
  for (const file of instructionFiles(options.clients)) {
    changes.push({ client: null, file, action: await editText(path.join(options.root, file), (text) => withBlock(text, AGENT_INSTRUCTION)) });
  }
  return changes;
}

export async function uninstallAgents(options: RegistrationOptions): Promise<RegistrationChange[]> {
  const changes: RegistrationChange[] = [];
  for (const client of options.clients) {
    const layout = LAYOUTS[client];
    changes.push({ client, file: layout.config, action: await editJson(path.join(options.root, layout.config), (config) => {
      if (!isRecord(config[layout.serversKey]) || !(SERVER_NAME in (config[layout.serversKey] as object))) return config;
      const servers = Object.fromEntries(Object.entries(config[layout.serversKey] as Record<string, unknown>).filter(([name]) => name !== SERVER_NAME));
      const rest = { ...config, [layout.serversKey]: servers };
      return Object.keys(servers).length === 0 && Object.keys(config).length === 1 ? null : rest;
    }, false) });
  }
  for (const file of instructionFiles(options.clients)) {
    changes.push({ client: null, file, action: await editText(path.join(options.root, file), (text) => withBlock(text, null), false) });
  }
  return changes;
}

function instructionFiles(clients: readonly AgentClient[]): string[] {
  return [...new Set(clients.map((client) => LAYOUTS[client].instruction))].sort();
}

/** Replaces, adds, or removes the marked block, leaving everything else as written. */
export function withBlock(text: string, block: string | null): string {
  const start = text.indexOf(BEGIN);
  const end = text.indexOf(END);
  if (start !== -1 && end > start) {
    const before = text.slice(0, start);
    const after = text.slice(end + END.length).replace(/^\n/, "");
    if (block !== null) return `${before}${block}${after}`;
    const head = before.replace(/\n+$/, "");
    const tail = after.replace(/^\n+/, "");
    if (head === "") return tail;
    return tail === "" ? `${head}\n` : `${head}\n\n${tail}`;
  }
  if (block === null) return text;
  return text.trim() === "" ? block : `${text.replace(/\n*$/, "\n")}\n${block}`;
}

async function editJson(file: string, edit: (config: Record<string, unknown>) => Record<string, unknown> | null, create = true): Promise<RegistrationChange["action"]> {
  const existing = await readText(file);
  if (existing === null && !create) return "absent";
  let config: Record<string, unknown> = {};
  if (existing !== null) {
    const parsed = JSON.parse(existing) as unknown;
    if (!isRecord(parsed)) throw new Error(`${file} is not a JSON object; fix or remove it before registering Web Doctor`);
    config = parsed;
  }
  const next = edit(config);
  if (next === null) {
    await fs.rm(file);
    return "removed";
  }
  const text = `${JSON.stringify(next, null, 2)}\n`;
  if (existing !== null && (text === existing || JSON.stringify(next) === JSON.stringify(config))) return "unchanged";
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, text);
  return existing === null ? "created" : "updated";
}

async function editText(file: string, edit: (text: string) => string, create = true): Promise<RegistrationChange["action"]> {
  const existing = await readText(file);
  if (existing === null && !create) return "absent";
  const next = edit(existing ?? "");
  if (existing !== null && next === existing) return "unchanged";
  if (next.trim() === "") {
    if (existing === null) return "unchanged";
    await fs.rm(file);
    return "removed";
  }
  await fs.writeFile(file, next);
  return existing === null ? "created" : "updated";
}

async function readText(file: string): Promise<string | null> {
  try {
    return await fs.readFile(file, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw error;
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
